### ISSUE TITLE
hello world用例自旋锁一直lock

### ISSUE THREAD

**Issue by fdgggy** [openlinyou/openthread#2]
windows平台下，主线程一直收不到Test0Thread线程发送的stop指令，导致主线程一直打印不出Pause，原因是自旋锁一直在lock
void lock() { while (flag_.test_and_set(std::memory_order_acquire)); }

**Comment by fdgggy** [comment]
找到问题了，自旋锁的flag没有初始化导致的，这样就可以了。std::atomic_flag flag_ = ATOMIC_FLAG_INIT;

**Comment by OpenMiniServer** [comment]
fix it.
